version: "3.9"
services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - fullstack

  app:
    container_name: microservice
    build:
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - redis
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge

volumes:
  redis-data: