version: "3.9"
services:
  redis:
    image: redis
    container_name: redis_user
    volumes:
      - ./redis-data:/bitnami/redis/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - fullstack

  app:
    container_name: microservice
    build:
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - redis
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge